services:
  web-app-blue:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    container_name: web-app-blue
    ports:
      - "8081:5000"
    environment:
      - APP_COLOR=blue
      - APP_NAME=Mavi Sürüm
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server
    networks:
      - devops_net

  web-app-green:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    container_name: web-app-green
    ports:
      - "8082:5000"
    environment:
      - APP_COLOR=green
      - APP_NAME=Yeşil Sürüm
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server
    networks:
      - devops_net

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-app-blue
      - web-app-green
    networks:
      - devops_net

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - devops_net
    restart: always # 👈 Kapanırsa tekrar açılması için

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - devops_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - devops_net

  redis-server:
    image: "redis:alpine"
    container_name: redis-server
    volumes:
      - redis_data:/data
    networks:
      - devops_net

volumes:
  redis_data:

networks:
  devops_net:
    driver: bridge
