services:
  # 🔵 Mavi Sürüm
  web-app-blue:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    ports:
      - "8081:5000"
    environment:
      - APP_COLOR=blue
      - APP_NAME=Mavi Sürüm
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  # 🟢 Yeşil Sürüm
  web-app-green:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    ports:
      - "8082:5000"
    environment:
      - APP_COLOR=green
      - APP_NAME=Yeşil Sürüm
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  # 👮‍♂️ Nginx Load Balancer
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-app-blue
      - web-app-green

  # 📊 cAdvisor (Monitoring)
  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "8080:8080"
    environment:
      # 🔑 KRİTİK DÜZELTME: cAdvisor'a Docker API sürümünü zorla 1.44 yaptırıyoruz
      - DOCKER_API_VERSION=1.44
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # 🗄️ Redis
  redis-server:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
